### PR TITLE
add single header magic

### PR DESCRIPTION
**Pull request by scalarwaves**
Pertaining to #112 This header is a start for binding to other languages.

Having all core header files in one place makes importing the library version of Gwion much simpler.

Based on this [gist](https://gist.github.com/fennecdjay/b98274766daef70ab4467c2b62e79511) by fennecdjay.

### CODE REVIEW

**Comment by fennecdjay** [comment]
Nice! :champagne: 
I'm a bit worried with the `../` thing thought.
Can't you use something like `-I../ast/include -I../util/include` ?
It would save us the `../` and gain some flexibility.

**Comment by scalarwaves** [comment]
Your solution is more elegant, I returned it to its original state.

**Comment by fennecdjay** [comment]
Looking Good!
Is there anything you want to add for this particular PR?
If not I'll merge as soon as the test succeed (wondering why travis is not showing up).

Does it mean you had some success with codegen?

**Comment by fennecdjay** [comment]
Looks Good! Merging :champagne: 
Thank you @scalarwaves.

**Pull request merged**
