### PR TITLE
Add fixes compile portaudio and jack

### PR DESCRIPTION
**Pull request by originalsouth**
Awesome project. 
Added fixes to compile portaudio and jack.

### CODE REVIEW

**Comment by fennecdjay** [comment]
Also, this builds shows a hang in tests system I have not investigated yet.

**Comment by originalsouth** [comment]
> Could you make those little changes and check if it works on your platform?
> 
> IMO, It would be better to:
> 
> not add GWION_CTL_PAdefine
> declare sp_data* sp;
> vm->bbq->sp to sp in callbacks.

Done :)

Out of curiosity, what platform are you using?
I'm using Archlinux.

**Comment by fennecdjay** [comment]
>Out of curiosity, what platform are you using?
I'm using Archlinux.

So do I 😃

**Comment by fennecdjay** [comment]
Mergin now :tada

**Comment by originalsouth** [comment]
Awesome! Happy to contribute :)

**Pull request merged**
