### PR TITLE
:wrench: Add Action to Cancel previous Workflows, if newer has been added

### PR DESCRIPTION
**Pull request by evayde**
This should solve #187 "Newer workflows should cancel older ones."

### CODE REVIEW

**Comment by fennecdjay** [comment]
Looks good to me!
Anything you want to add before I merge?

**Comment by evayde** [comment]
No, I am okay with it. But we might want to consider adding a section to the Readme for any Action that will be added in the future. Since I had to manually add every ID for Actions I want to stop (see comments in `cancel.yml`).

**Comment by fennecdjay** [comment]
> But we might want to consider adding a section to the Readme for any Action that will be added in the future.

Seems sensible. Maybe a `CI` page in the docs? I'd be glad to have your thoughts on it.
Merging now, Thank you!

**Comment by fennecdjay** [comment]
@all-contributors please add evayde  for code.

**Pull request merged**
