### PR TITLE
:book: Update README to add instructions to execute Hello World Program

### PR DESCRIPTION
**Pull request by Pranav2612000**
Add steps for users to write their first program. 
Suggestions welcome.

### CODE REVIEW

**Comment by fennecdjay** [comment]
The writing is pretty good :tada:

The only thing I see is that you use installation where it is in fact compilation.
My bad, installation is not documented, and probably needs to be checked (nice cath!).

The build is failing at the moment but this shall not be an issue as only the README is changed. However it might be that CI system is invalid for merge.

If you're OK, I'll merge this right now.


------

I'm very grateful for how much issue you uncover.
I hope you're doing well and I'm looking forward reading you.

**Comment by fennecdjay** [comment]
As a side note, I just checked `install` target.
It seems OK, just missing the static library.
I'm doing this now and I'll merge after.
[util](https://github.com/fennecdjay/gwion-util) and [ast](https://github.com/fennecdjay/gwion-ast) are fine in this regard.

Maybe we have to provide installation instructions.

**Comment by fennecdjay** [comment]
@all-contributors please add @Pranav2612000  for Documentation.

**Comment by Pranav2612000** [comment]
Is there anything else that needs to be updated?

**Comment by fennecdjay** [comment]
Nice to see you again.
You can look #179,
that'd be pretty great if you take care of this issue, your writing skills are so much better than mine!!

Would you like to join in a team?
Also, I'm planning to add 'long' as a type for `long long int`, this would require some work in the VM, interresting but not to hard. I you fancy doing it, I'll provide some documentation about the VM.

**Comment by Pranav2612000** [comment]
Yup. I'll definitely like to work in the VM. I may require help, but I am interested. Could you share the documentation about the VM?
I'll also put up a PR to the documentation issue soon.

**Comment by fennecdjay** [comment]
> Could you share the documentation about the VM?

I got to write them first, but I'll do soon :confused:

> I'll also put up a PR to the documentation issue soon.

Feel free to do as many documentation PR as you want, you really write things clear, I appreciate that.

...

Anyway the `long` issue should not be to hard to tackle, while being a nice way to get started with the VM :smile:

**Comment by fennecdjay** [comment]
@Pranav2612000, while preparing instructions for the long (long) thing, I noticed the size of `m_int` would be enough to hold big numbers (at least on 64-bit systems), so I modified the incorrect bit in the lexer. Gwion is now ready to some some [Euler project](https://projecteuler.net/) problems :smile:

This is unrelated, but I'm wondering if you got notified when are created discussion in the organization?

**Comment by Pranav2612000** [comment]
Hi @fennecdjay . 
I was busy the past few weeks, preparing & appearing for campus placement drives and jobs. I just received an offer yesterday, so I think I'll get time this weekend to go through the tasks. Is there anything specific that you'll like me to?

**Comment by fennecdjay** [comment]
@Pranav2612000, thanks for your reply, I hope you'll be happy with the offer you received.
I'm afraid I didn't update the tasks for Gwion but here's a couple of things you could do:
  * make the [WebSocket](https://github.com/fennecdjay/Gwion-plug/tree/master/WebSocket) driver work with secured encryption, so that we can have gwion run and output sound on, say, [anyfiddle](https://www.anyfiddle.com/). That would be a **huge** win! :champagne:
  * recently memory pools have been improved, but most of the calls could directly point to the pool index. (I know that's not clear, let me know if you're interrested, I'll write something better on this topic).
  * exp_dot locations could include id. This requires changing new_exp_dot so that it takes a `loc_t` as argument, and changing call sites (in gwion.y, use `GET_LOC(&@$)` to get full parser location). This is a low hanging fruit, could be pretty quick to do.

Cheers!

**Comment by fennecdjay** [comment]
@Pranav2612000, it is not clear for me wether you are notified of discussion in the organization. Could you tell me if it is the case?

**Pull request merged**
