### PR TITLE
:book: Add Installation instructions

### LINKED ISSUE #179: Doc: Installation procedure should be documented in the README
After the [first code](https://github.com/fennecdjay/Gwion#executing-your-first-code-hello_worldgw) section, there should be some info about how installing Gwion.

That's basically `make install`.

### PR DESCRIPTION
**Pull request by a-mere-peasant**
closes #179

### CODE REVIEW

**Comment by fennecdjay** [comment]
I like it! Are you OK to merge?

**Comment by a-mere-peasant** [comment]
> I like it! Are you OK to merge?

Yes,ready to merge.

**Comment by a-mere-peasant** [comment]
sorry i forgot to skip ci .I'll keep that in mind the next time

**Comment by fennecdjay** [comment]
@all-contributors please add a-mere-peasant for documentation.

**Comment by a-mere-peasant** [comment]
i think the bot might have added someone else

**Comment by fennecdjay** [comment]
It looks like this. I'll make the changes by hand. I suppose we should file them an issue. I already contributed to that project, they are very friendly.

**Comment by a-mere-peasant** [comment]
> It looks like this. I'll make the changes by hand. I suppose we should file them an issue. I already contributed to that project, they are very friendly.

I think it's something to do with the hyphen,probably the method to search expressions.Let me know if I can help in any way 
 
> Since it's october, I'd rather not do it myself, but rather create an issue (or you can just PR the fixes). It is just editing line 123 of `README.md` with your infos instead [link](https://github.com/fennecdjay/Gwion/edit/master/README.md#L123).

I have already completed my PRs for hacktoberfest so I think it would be helpful for someone else to do it and complete their PRs as well 
> Sorry for not noticing it, usually the bot works flawlessly.

No problem :)

**Pull request merged**
