### PR TITLE
Fix #208

### LINKED ISSUE #208: CodeQl actions should respect [skip ci]
There is no use in running CodeQl checks if `[skip ci]` is requested.
Please edit [this file](https://github.com/fennecdjay/Gwion/blob/master/.github/workflows/codeql-analysis.yml) so that it works as the others.
Examples can be found in [here](https://github.com/fennecdjay/Gwion/blob/master/.github/workflows/linux.yml#L17)

### PR DESCRIPTION
**Pull request by deekts**
Added an if condition to the analyze job.

### CODE REVIEW

**Comment by fennecdjay** [comment]
Looks good to me!
Are you OK to merge?

**Comment by deekts** [comment]
Yes

**Comment by fennecdjay** [comment]
Thank you.

**Comment by fennecdjay** [comment]
@allcontributors-bot please add @deekts for code.

**Comment by fennecdjay** [comment]
@all-contributors please add deekts for code

**Pull request merged**
